config/routes.rb
Rails.application.routes.draw do
  resources :current_weathers do
    get 'dashboard', on: :collection
    post 'geolocation', on: :collection
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "current_weathers#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current_weather.rb
class CurrentWeather < ApplicationRecord
  include Services::OpenWeather

  validates :latitude, :longitude, presence: true
  validates :latitude, :longitude, numericality: true

  def self.by_location(latitude, longitude)
    record = where(latitude: latitude, longitude: longitude).where('created_at > ?', Time.now.utc - 1.hour).first_or_initialize
    unless record.persisted?
      response = current_weather_by_location(latitude, longitude)
      record.save_weather(response)
      record.save
    end
    record
  end

  def self.by_city(city)
    record = where('name LIKE ?', '%' + city + '%').where('created_at > ?', Time.now.utc - 1.hour).first_or_initialize
    unless record.persisted?
      response = current_weather_by_city(city)
      record.save_weather(response)
      record.save
    end
    record
  end

  def save_weather(response)
    self.name = response['name']
    self.latitude = response['coord']['lat']
    self.longitude = response['coord']['lon']
    self.country = response['sys']['country']
    self.temperature = response['main']['temp']
    self.feels_like = response['main']['feels_like']
    self.humidity = response['main']['humidity']
    self.wind_speed = response['wind']['speed']
    self.weather_main = response['weather'].first['main']
    self.weather_description = response['weather'].first['description']
    self.icon = response['weather'].first['icon']
    self.temp_min = response['main']['temp_min']
    self.temp_max = response['main']['temp_max']
    self.full_response = response.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/current_weathers_controller.rb
class CurrentWeathersController < ApplicationController
  before_action :set_current_weather, only: %i[ show edit update destroy ]

  def dashboard
    if params[:city]
      @current_weather = CurrentWeather.by_city(params[:city])
    elsif params[:latitude] && params[:longitude]
      @current_weather = CurrentWeather.by_location(params[:latitude], params[:longitude])
    end

    respond_to do |format|
      format.html
    end
  end

  def geolocation
    location = Geocoder.search([params[:latitude], params[:longitude]]).first
    render json: location.data
  end

  # GET /current_weathers or /current_weathers.json
  def index
    @current_weathers = CurrentWeather.all
  end

  # GET /current_weathers/1 or /current_weathers/1.json
  def show
  end

  # GET /current_weathers/new
  def new
    @current_weather = CurrentWeather.new
  end

  # GET /current_weathers/1/edit
  def edit
  end

  # POST /current_weathers or /current_weathers.json
  def create
    @current_weather = CurrentWeather.new(current_weather_params)

    respond_to do |format|
      if @current_weather.save
        format.html { redirect_to current_weather_url(@current_weather), notice: "Current weather was successfully created." }
        format.json { render :show, status: :created, location: @current_weather }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @current_weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_weathers/1 or /current_weathers/1.json
  def update
    respond_to do |format|
      if @current_weather.update(current_weather_params)
        format.html { redirect_to current_weather_url(@current_weather), notice: "Current weather was successfully updated." }
        format.json { render :show, status: :ok, location: @current_weather }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @current_weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_weathers/1 or /current_weathers/1.json
  def destroy
    @current_weather.destroy!

    respond_to do |format|
      format.html { redirect_to current_weathers_url, notice: "Current weather was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_weather
      @current_weather = CurrentWeather.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def current_weather_params
      params.require(:current_weather).permit(:latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_weathers_helper.rb
module CurrentWeathersHelper
  def weather_icon(icon_name)
    icon_url = "https://openweathermap.org/img/wn/#{icon_name}@2x.png"
    image_tag(icon_url, alt: 'Weather icon', class: 'w-48 h-48')
  end
end

app/views/current_weathers/_current_weather.html.erb
<div id="<%= dom_id current_weather %>">
  <p>
    <strong>Latitude:</strong>
    <%= current_weather.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= current_weather.longitude %>
  </p>

</div>

app/views/current_weathers/_form.html.erb
<%= form_with(model: current_weather) do |form| %>
  <% if current_weather.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(current_weather.errors.count, "error") %> prohibited this current_weather from being saved:</h2>

      <ul>
        <% current_weather.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/current_weathers/dashboard.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Current weathers" %>

<div class="flex items-center justify-center">
  <div class="flex flex-col w-full max-w-fit">

    <!-- Search box -->
    <div class="min-w-full my-4">
      <h1 class="font-bold text-3xl mb-4 text-white">Search by location</h1>
      <div data-controller="geolocation">
        <%= form_with url: dashboard_current_weathers_url, method: :get do %>
          <div class="relative">
            <%= text_field_tag :city, nil, 
                class: "px-6 py-3 rounded border border-gray-300/80 focus:ring-4 focus:ring-gray-200/60 focus:outline-none w-full rounded-full text-lg", 
                placeholder: "Search city", 
                data: { geolocation_target: 'searchWeather' } %>

            <button type="submit" class="absolute top-1.5 right-2 bg-white rounded-full px-5 py-2 border border-gray-300/80 shadow-sm bg-gray-50/50 hover:bg-gray-50">Search</button>
          </div>
        <% end %>

        <button type="button" data-action="click->geolocation#handleClick" class="underline font-medium mt-2 text-white">
          <span>Find my location</span>
        </button>
      </div>
    </div>


    <!-- Current weather -->
    <div class="card text-white shadow-sm shadow-neutral-400">
      <div id="current-weather" class="m-0 p-0 border-0 align-baseline block bg-zinc-600 rounded" >

        <!-- Weather header -->
        <div id="weather-header" class="pt-5 pl-5 pr-5 pb-2.5 border-0 m-0 block" >
          <div class="flex flex-row justify-between items-start" >
            <div id="weather-current-status" >
              <h1 class="text-3xl font-bold" >
                <%= @current_weather.weather_main unless @current_weather.nil? %>
              </h1>
            </div>
            <div class="text-xs mt-2 flex flex-col items-end" >
              <div>Min: <%= @current_weather.temp_min.round unless @current_weather.nil? %>°</div>
              <div>Max: <%= @current_weather.temp_max.round unless @current_weather.nil? %>°</div>
            </div>
          </div>
          <div id="weather-location" class="w-full text-base">
            <% if @current_weather && @current_weather.name %>
              <%= @current_weather.name unless @current_weather.nil? %>
            <% else %>
              Lat: <%= @current_weather.latitude unless @current_weather.nil? %>, Long: <%= @current_weather.longitude unless @current_weather.nil? %>
            <% end %>
            <p>
              <%= @current_weather.country unless @current_weather.nil? %>
            </p>
          </div>
        </div>

        <!-- Weather body -->
        <div class="flex items-center mr-4 justify-around" >
          <div class="pb-2">
            <%= weather_icon(@current_weather.icon) unless @current_weather.nil? %>
          </div>
          <div class="ml-5">
            <div class="text-7xl flex flex-row items-end" >
              <%= @current_weather.temperature.round unless @current_weather.nil? %>
              <span class="text-3xl" >F°</span>
            </div>
            <div class="ml-2" >
              Real Feel: <%= @current_weather.feels_like.round unless @current_weather.nil? %>°
            </div>
          </div>
        </div>

        <!-- Weather footer -->
        <div class="flex items-center justify-around pb-4" >
          <div class="">
            Humidity: <%= @current_weather.humidity unless @current_weather.nil? %>
          </div>
          <div class="">
            Wind Speed: <%= @current_weather.wind_speed unless @current_weather.nil? %>
          </div>
        </div>
        
      </div>
    </div>
  </div>

app/views/current_weathers/edit.html.erb
<% content_for :title, "Editing current weather" %>

<h1>Editing current weather</h1>

<%= render "form", current_weather: @current_weather %>

<br>

<div>
  <%= link_to "Show this current weather", @current_weather %> |
  <%= link_to "Back to current weathers", current_weathers_path %>
</div>

app/views/current_weathers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Current weathers" %>

<h1>Current weathers</h1>

<div id="current_weathers">
  <% @current_weathers.each do |current_weather| %>
    <%= render current_weather %>
    <p>
      <%= link_to "Show this current weather", current_weather %>
    </p>
  <% end %>
</div>

<%= link_to "New current weather", new_current_weather_path %>

app/views/current_weathers/new.html.erb
<% content_for :title, "New current weather" %>

<h1>New current weather</h1>

<%= render "form", current_weather: @current_weather %>

<br>

<div>
  <%= link_to "Back to current weathers", current_weathers_path %>
</div>

app/views/current_weathers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @current_weather %>

<div>
  <%= link_to "Edit this current weather", edit_current_weather_path(@current_weather) %> |
  <%= link_to "Back to current weathers", current_weathers_path %>

  <%= button_to "Destroy this current weather", @current_weather, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-neutral-900" >
  <head>
    <title><%= content_for(:title) || "Acima Weather Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5  ">
      <%= yield %>
    </main>
  </body>
</html>